Skip jsdoc checks on windows due to https://github.com/nodejs/node/issues/52554
Failure is like:
  1) JSDoc contains all methods
       "before all" hook for "Database":
     Error: spawn EINVAL
      at ChildProcess.spawn (node:internal/child_process:414:11)
      at spawn (node:child_process:761:9)
      at execFile (node:child_process:351:17)
      at jsdocParser (node_modules\jsdoc3-parser\index.js:58:3)
      at node:internal/util:441:7
      at new Promise (<anonymous>)
      at jsdocParser (node:internal/util:427:12)

unsure whether jsdocParser can be bumped, but looks to be broken still.